# .github/workflows/android.yml
name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

       # This step manually deletes old build folders to ensure a clean state.
      - name: Force Clean Workspace
        run: |
          echo "Deleting old build directories..."
          rm -rf $GITHUB_WORKSPACE/*.*
          rm -rf $GITHUB_WORKSPACE/app/build
          rm -rf $GITHUB_WORKSPACE/.gradle
          echo "Workspace cleaned."

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # This step manually deletes old build folders to ensure a clean state.
      - name: Force Clean Workspace
        run: |
          echo "Deleting old build directories..."
          rm -rf 
          rm -rf $GITHUB_WORKSPACE/app/build
          rm -rf $GITHUB_WORKSPACE/.gradle
          echo "Workspace cleaned."

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'
          # Disabling internal caching for this debug step
          cache-disabled: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # Disabling internal caching for this debug step
          cache: false
          cmdline-tools-version: 'latest'
          build-tools-version: '34.0.0'
          platform-version: '34'
          ndk-version: '25.2.9519653'

      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          # Run a clean build with extra info for debugging
          ./gradlew clean build --stacktrace 

      - name: List Generated APK Files
        run: ls -l app/build/outputs/apk/debug/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BWCTrans-debug
          path: app/build/outputs/apk/debug/app-debug.apk
